services:
  pgvector:
    container_name: rag-agpgdb
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=vectordb'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=admin'
    volumes:
      - agentic_rag_chatbot_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - agentic-chatbot-net
volumes:
  agentic_rag_chatbot_data:
networks:
  agentic-chatbot-net:
    driver: bridge